"""Structural grounding provenance for Autoanosis AI responses.

This module reports which *categories* of personal context were actually included
in the formatted prompt. It deliberately never copies medical values, names,
notes, document titles, or other PHI into the provenance payload.
"""

from __future__ import annotations

from typing import Any

SECTION_LABELS = {
    "profile": "Προφίλ",
    "medications": "Φάρμακα",
    "exams": "Εξετάσεις",
    "best": "BEST",
    "checkins": "Check-ins",
    "health_notes": "Σημειώσεις υγείας",
    "health_tracking": "Παρακολούθηση υγείας",
    "medication_schedule": "Πρόγραμμα φαρμάκων",
    "weekly_trends": "Τάσεις εβδομάδας",
    "medical_documents": "Ιατρικά έγγραφα",
}

# Markers are generated by build_selective_context()/builder adapters. Matching
# only these fixed headings keeps the manifest tied to text that actually entered
# the model prompt, instead of claiming every field supplied by the client was used.
SECTION_MARKERS = {
    "profile": ("1. ΠΡΟΦΙΛ:", "ΠΡΟΣΩΠΙΚΑ ΙΑΤΡΙΚΑ ΔΕΔΟΜΕΝΑ ΧΡΗΣΤΗ:", "Χρήστης:", "Πάθηση:"),
    "medications": ("2. ΦΑΡΜΑΚΑ:", "Φάρμακα:"),
    "exams": ("3. ΕΞΕΤΑΣΕΙΣ & ΙΑΤΡΙΚΑ ΕΓΓΡΑΦΑ:", "ΑΝΑΛΥΤΙΚΑ ΑΠΟΤΕΛΕΣΜΑΤΑ:"),
    "best": ("4. BEST HISTORY:",),
    "checkins": ("5. RECENT CHECK-INS:", "Μέσοι όροι τελευταίων ημερών"),
    "health_notes": ("6. HEALTH NOTES:",),
    "health_tracking": ("7. HEALTH TRACKING:",),
    "medication_schedule": ("8. MEDICATION SCHEDULE:",),
    "weekly_trends": ("9. ΤΑΣΕΙΣ ΕΒΔΟΜΑΔΑΣ:",),
    "medical_documents": ("10. ΑΡΧΕΙΟ ΕΓΓΡΑΦΩΝ", "ΙΑΤΡΙΚΑ ΕΓΓΑΦΑ (δομημένο περιεχόμενο):"),
}


def _count_list(value: Any) -> int | None:
    return len(value) if isinstance(value, list) else None


def _nested_recent_count(ctx: dict[str, Any]) -> int | None:
    direct = _count_list(ctx.get("recent_checkins"))
    if direct is not None:
        return direct
    daily = ctx.get("daily_checkins")
    if isinstance(daily, dict):
        return _count_list(daily.get("recent"))
    return None


def _medication_count(ctx: dict[str, Any]) -> int | None:
    meds = ctx.get("medications")
    if isinstance(meds, list):
        return len(meds)
    if isinstance(meds, dict):
        current = meds.get("current_medications")
        if isinstance(current, list):
            return len(current)
    return None


def _exam_count(ctx: dict[str, Any]) -> int | None:
    summary = ctx.get("exams_summary")
    if isinstance(summary, dict):
        for key in ("report_count", "result_count"):
            value = summary.get(key)
            if isinstance(value, int) and value >= 0:
                return value
    for key in ("report_summary", "structured_exam_results", "test_results"):
        value = ctx.get(key)
        if isinstance(value, list):
            return len(value)
    return None


def _document_count(ctx: dict[str, Any]) -> int | None:
    counts: list[int] = []
    for key in (
        "medical_documents",
        "medical_document_context",
        "structured_medical_documents",
    ):
        value = ctx.get(key)
        if isinstance(value, list):
            counts.append(len(value))
    return max(counts) if counts else None


def _best_count(ctx: dict[str, Any]) -> int | None:
    history = ctx.get("best_history")
    if isinstance(history, list):
        return len(history) + (1 if ctx.get("best_protocol") else 0)
    return 1 if ctx.get("best_protocol") else None


COUNT_READERS = {
    "medications": _medication_count,
    "exams": _exam_count,
    "best": _best_count,
    "checkins": _nested_recent_count,
    "medical_documents": _document_count,
}


def build_grounding_manifest(
    wp_context: dict[str, Any] | None,
    snapshot: str,
    snapshot_source: str,
    intent: str,
) -> dict[str, Any]:
    """Return non-sensitive metadata about context that actually entered the prompt."""
    safe_context = wp_context if isinstance(wp_context, dict) else {}
    formatted = snapshot if isinstance(snapshot, str) else ""

    sections: list[dict[str, Any]] = []
    if formatted.strip():
        for section_id, markers in SECTION_MARKERS.items():
            if not any(marker in formatted for marker in markers):
                continue

            item: dict[str, Any] = {
                "id": section_id,
                "label": SECTION_LABELS[section_id],
            }
            reader = COUNT_READERS.get(section_id)
            if reader:
                count = reader(safe_context)
                if isinstance(count, int):
                    item["count"] = count
            sections.append(item)

    return {
        "grounded": bool(formatted.strip()),
        "intent": intent,
        "context_source": snapshot_source if formatted.strip() else "none",
        "sections": sections,
        # Size is diagnostic only. It proves context was present without exposing it.
        "context_bytes": len(formatted.encode("utf-8")) if formatted else 0,
    }


def manifest_contains_sensitive_values(manifest: dict[str, Any], forbidden_values: list[str]) -> bool:
    """Test helper: detect accidental leakage of supplied PHI strings."""
    serialized = repr(manifest)
    return any(value and value in serialized for value in forbidden_values)


def build_context_fact_index(wp_context: dict[str, Any] | None) -> dict[str, Any]:
    """Build a PHI-free structural index of authoritative medical context.

    This is a read-model only. It does not persist or duplicate medical records.
    It reports source families, record counts and temporal coverage where the
    source already provides a date/timestamp.
    """
    ctx = wp_context if isinstance(wp_context, dict) else {}

    def date_span(values: list[str]) -> dict[str, str] | None:
        clean = sorted({v for v in values if isinstance(v, str) and v.strip()})
        if not clean:
            return None
        return {"from": clean[0], "to": clean[-1]}

    index: dict[str, Any] = {}

    meds = ctx.get("medications")
    if isinstance(meds, list):
        dates = [
            str(item.get("start_date"))
            for item in meds
            if isinstance(item, dict) and item.get("start_date")
        ]
        index["medications"] = {
            "source": "ame",
            "resource": "mm_medications",
            "count": len(meds),
            "coverage": date_span(dates),
        }

    today = ctx.get("today_doses")
    if isinstance(today, dict) and isinstance(today.get("doses"), list):
        doses = today["doses"]
        dates = [
            str(item.get("scheduled_local_date"))
            for item in doses
            if isinstance(item, dict) and item.get("scheduled_local_date")
        ]
        index["doses"] = {
            "source": "ame",
            "resource": "mm_doses",
            "count": len(doses),
            "coverage": date_span(dates),
        }

    analytics = ctx.get("longitudinal_checkin_analytics")
    if isinstance(analytics, dict) and isinstance(analytics.get("recent_records"), list):
        records = analytics["recent_records"]
        dates = [
            str(item.get("date"))
            for item in records
            if isinstance(item, dict) and item.get("date")
        ]
        index["checkins"] = {
            "source": "autoa_checkins",
            "resource": "daily_checkins",
            "count": len(records),
            "coverage": date_span(dates),
        }

    exam_results = ctx.get("structured_exam_results")
    if isinstance(exam_results, list):
        dates = [
            str(item.get("test_date"))
            for item in exam_results
            if isinstance(item, dict) and item.get("test_date")
        ]
        index["exam_results"] = {
            "source": "render_exams",
            "resource": "structured_exam_results",
            "count": len(exam_results),
            "coverage": date_span(dates),
        }

    narrative = ctx.get("narrative_exam_context")
    if isinstance(narrative, list):
        dates = [
            str(item.get("performed_at"))
            for item in narrative
            if isinstance(item, dict) and item.get("performed_at")
        ]
        index["exam_reports"] = {
            "source": "render_exams",
            "resource": "narrative_exam_context",
            "count": len(narrative),
            "coverage": date_span(dates),
        }

    documents = ctx.get("medical_document_context")
    if isinstance(documents, list):
        dates = [
            str(item.get("date"))
            for item in documents
            if isinstance(item, dict) and item.get("date")
        ]
        index["medical_documents"] = {
            "source": "render_documents",
            "resource": "medical_document_context",
            "count": len(documents),
            "coverage": date_span(dates),
        }

    return index
